services:
  - type: web
    name: the-living-rack
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: living-rack-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: living-rack-db
    plan: free
